In [1]:
import pandas as pd
import numpy as np

In [2]:
# =========================
# Task 1: Creating DataFrames
# =========================

# Project DataFrame
project_data = {
    "ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"],
    "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5","Project 6","Project 7",
                "Project 8","Project 9","Project 10","Project 11","Project 12","Project 13","Project 14"],
    "Cost": [1002000,2000000,4500000,5500000,np.nan,680000,400000,350000,np.nan,300000,2000000,1000000,3000000,200000],
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished",
               "Failed","Ongoing","Finished","Failed","Ongoing","Finished","Finished"]
}

df_project = pd.DataFrame(project_data)


# Employee DataFrame
employee_data = {
    "ID": ["A001","A002","A003","A004","A005"],
    "Name": ["John Alter","Alice Luxumberg","Tom Sabestine","Nina Adgra","Amy Johny"],
    "Gender": ["M","F","M","F","F"],
    "City": ["Paris","London","Berlin","Newyork","Madrid"],
    "Age": [25,27,29,31,30]
}

df_employee = pd.DataFrame(employee_data)


# Seniority Level DataFrame
seniority_data = {
    "ID": ["A001","A002","A003","A004","A005"],
    "Designation Level": [2,2,3,2,3]
}

df_seniority = pd.DataFrame(seniority_data)


# Display DataFrames
print("Project DataFrame")
display(df_project)

print("Employee DataFrame")
display(df_employee)

print("Seniority Level DataFrame")
display(df_seniority)

Project DataFrame

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

Employee DataFrame

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

Seniority Level DataFrame

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [3]:
# Save DataFrames to CSV files
df_project.to_csv("project.csv", index=False)
df_employee.to_csv("employee.csv", index=False)
df_seniority.to_csv("seniority.csv", index=False)

print("Task 1 completed and saved!")

Task 1 completed and saved!

In [4]:
# ==========================================
# Task 2: Fill Missing Cost using Running Average
# ==========================================

# Variable to store sum of previous costs
total = 0

# Variable to count valid costs
count = 0

# Loop through rows
for i in range(len(df_project)):
    
    # If cost is not missing
    if not pd.isna(df_project.loc[i, "Cost"]):
        
        # Add to total
        total += df_project.loc[i, "Cost"]
        
        # Increase count
        count += 1
    
    # If cost is missing
    else:
        
        # Calculate running average
        avg = total / count
        
        # Replace missing value
        df_project.loc[i, "Cost"] = avg


# Display after filling
print("After Filling Missing Values:")
display(df_project)

After Filling Missing Values:

      ID     Project          Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  3.250500e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  2.061714e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

In [5]:
# Save updated project file
df_project.to_csv("project.csv", index=False)

print("Task 2 completed and saved!")

Task 2 completed and saved!

In [6]:
# ==========================================
# Task 3: Split Name into First and Last Name
# ==========================================

# Split the Name column into two parts
df_employee[["First Name", "Last Name"]] = df_employee["Name"].str.split(" ", expand=True)

# Drop old Name column
df_employee = df_employee.drop("Name", axis=1)

# Display after splitting
print("After Splitting Name:")
display(df_employee)

After Splitting Name:

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [7]:
# Save updated employee file
df_employee.to_csv("employee.csv", index=False)

print("Task 3 completed and saved!")

Task 3 completed and saved!

In [8]:
# ==========================================
# Task 4: Merge Project and Employee Data
# ==========================================

# Merge on ID column
df_merge1 = pd.merge(df_project, df_employee, on="ID", how="inner")

# Display result
print("After First Merge:")
display(df_merge1)

After First Merge:

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Amy,Johny
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,John,Alter
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny

In [9]:
# ==========================================
# Merge with Seniority Data
# ==========================================

# Final merge
df_final = pd.merge(df_merge1, df_seniority, on="ID", how="inner")

# Display final merged data
print("Final Merged Data:")
display(df_final)

Final Merged Data:

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,2
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3

In [10]:
# Save merged data
df_final.to_csv("final_data.csv", index=False)

print("Task 4 completed and saved!")

Task 4 completed and saved!

In [11]:
# =========================
# Task 5: Add Bonus Column
# =========================

# Create Bonus column
df_final["Bonus"] = 0

# Loop through rows
for i in range(len(df_final)):
    
    # If project is finished
    if df_final.loc[i, "Status"] == "Finished":
        
        # Calculate 5% bonus
        df_final.loc[i, "Bonus"] = df_final.loc[i, "Cost"] * 0.05
    
    # Otherwise bonus is 0
    else:
        df_final.loc[i, "Bonus"] = 0


# Display result
print("After Adding Bonus:")
display(df_final)

After Adding Bonus:

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2,50100
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2,0
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine,3,225000
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Amy,Johny,3,162525
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,2,0
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,20000
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine,3,0
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,John,Alter,2,0
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine,3,15000
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,2,0
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2,150000
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,10000

In [12]:
# Save updated file
df_final.to_csv("final_data.csv", index=False)
print("Task 5 completed and saved!")

Task 5 completed and saved!

In [13]:
# ==================================
# Task 6: Demote Designation for Failed
# ==================================

# Loop through rows
for i in range(len(df_final)):
    
    # If project status is Failed
    if df_final.loc[i, "Status"] == "Failed":
        
        # Increase designation level by 1 (demotion)
        df_final.loc[i, "Designation Level"] += 1


print("After Demotion:")
display(df_final)

After Demotion:

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2,50100
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2,0
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine,3,225000
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Amy,Johny,3,162525
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,3,0
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,20000
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine,4,0
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,John,Alter,2,0
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine,3,15000
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,3,0
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2,150000
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,10000

In [14]:
# ==================================
# Delete Invalid Designations
# ==================================

# Keep only rows where designation <= 4
df_final = df_final[df_final["Designation Level"] <= 4]

print("After Deleting Designation > 4:")
display(df_final)

After Deleting Designation > 4:

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2,50100
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2,0
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine,3,225000
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Amy,Johny,3,162525
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,3,0
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,20000
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine,4,0
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,John,Alter,2,0
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine,3,15000
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,3,0
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2,150000
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,10000

In [15]:
# Save updated file
df_final.to_csv("final_data.csv", index=False)

print("Task 6 completed and saved!")

Task 6 completed and saved!

In [16]:
# ==================================
# Task 7 : Add Mr. / Mrs. to First Name
# ==================================

# Loop through rows
for i in range(len(df_final)):
    
    # If Male
    if df_final.loc[i, "Gender"] == "M":
        
        df_final.loc[i, "First Name"] = "Mr. " + df_final.loc[i, "First Name"]
    
    # If Female
    elif df_final.loc[i, "Gender"] == "F":
        
        df_final.loc[i, "First Name"] = "Mrs. " + df_final.loc[i, "First Name"]


print("After Adding Mr/Mrs:")
display(df_final)

After Adding Mr/Mrs:

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,Mr. John,Alter,2,50100
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Mrs. Alice,Luxumberg,2,0
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Mr. Tom,Sabestine,3,225000
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Mrs. Nina,Adgra,2,0
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Mrs. Amy,Johny,3,162525
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Mrs. Alice,Luxumberg,3,0
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Mrs. Amy,Johny,3,20000
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Mr. Tom,Sabestine,4,0
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,Mr. John,Alter,2,0
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Mr. Tom,Sabestine,3,15000
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,Mr. John,Alter,3,0
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Mrs. Nina,Adgra,2,0
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Mrs. Nina,Adgra,2,150000
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Mrs. Amy,Johny,3,10000

In [17]:
# ==================================
# Drop Gender Column
# ==================================

df_final = df_final.drop("Gender", axis=1)

print("After Dropping Gender:")
display(df_final)

After Dropping Gender:

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1.002000e+06,Finished,Paris,25,Mr. John,Alter,2,50100
1,A002,Project 2,2.000000e+06,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0
2,A003,Project 3,4.500000e+06,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000
3,A004,Project 4,5.500000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0
4,A005,Project 5,3.250500e+06,Finished,Madrid,30,Mrs. Amy,Johny,3,162525
5,A002,Project 6,6.800000e+05,Failed,London,27,Mrs. Alice,Luxumberg,3,0
6,A005,Project 7,4.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,3,20000
7,A003,Project 8,3.500000e+05,Failed,Berlin,29,Mr. Tom,Sabestine,4,0
8,A001,Project 9,2.061714e+06,Ongoing,Paris,25,Mr. John,Alter,2,0
9,A003,Project 10,3.000000e+05,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000
10,A001,Project 11,2.000000e+06,Failed,Paris,25,Mr. John,Alter,3,0
11,A004,Project 12,1.000000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0
12,A004,Project 13,3.000000e+06,Finished,Newyork,31,Mrs. Nina,Adgra,2,150000
13,A005,Project 14,2.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,3,10000

In [18]:
# Save updated file
df_final.to_csv("final_data.csv", index=False)

print("Task 7 completed and saved!")

Task 7 completed and saved!

In [19]:
# ==================================
# Task 8 : Promote Based on Age
# ==================================

# Loop through rows
for i in range(len(df_final)):
    
    # If age > 29
    if df_final.loc[i, "Age"] > 29:
        
        # Decrease designation level by 1 (promotion)
        df_final.loc[i, "Designation Level"] -= 1


print("After Promotion:")
display(df_final)

After Promotion:

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1.002000e+06,Finished,Paris,25,Mr. John,Alter,2,50100
1,A002,Project 2,2.000000e+06,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0
2,A003,Project 3,4.500000e+06,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000
3,A004,Project 4,5.500000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,0
4,A005,Project 5,3.250500e+06,Finished,Madrid,30,Mrs. Amy,Johny,2,162525
5,A002,Project 6,6.800000e+05,Failed,London,27,Mrs. Alice,Luxumberg,3,0
6,A005,Project 7,4.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,2,20000
7,A003,Project 8,3.500000e+05,Failed,Berlin,29,Mr. Tom,Sabestine,4,0
8,A001,Project 9,2.061714e+06,Ongoing,Paris,25,Mr. John,Alter,2,0
9,A003,Project 10,3.000000e+05,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000
10,A001,Project 11,2.000000e+06,Failed,Paris,25,Mr. John,Alter,3,0
11,A004,Project 12,1.000000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,0
12,A004,Project 13,3.000000e+06,Finished,Newyork,31,Mrs. Nina,Adgra,1,150000
13,A005,Project 14,2.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,2,10000

In [20]:
# Save updated file
df_final.to_csv("final_data.csv", index=False)

print("Task 8 completed and saved!")

Task 8 completed and saved!

In [21]:
# ==================================
# Task 9 : Calculate Total Project Cost
# ==================================

# Dictionary to store total cost
total_cost = {}

# Loop through rows
for i in range(len(df_final)):
    
    emp_id = df_final.loc[i, "ID"]
    cost = df_final.loc[i, "Cost"]
    
    # Initialize if needed
    if emp_id not in total_cost:
        total_cost[emp_id] = 0
    
    # Add cost
    total_cost[emp_id] += cost


print("Total Cost Dictionary:")
print(total_cost)

Total Cost Dictionary:
{'A001': np.float64(5063714.285714285), 'A002': np.float64(2680000.0), 'A003': np.float64(5150000.0), 'A004': np.float64(9500000.0), 'A005': np.float64(3850500.0)}

In [22]:
# ==================================
# Get First Name Mapping
# ==================================

name_map = {}

for i in range(len(df_final)):
    
    emp_id = df_final.loc[i, "ID"]
    fname = df_final.loc[i, "First Name"]
    
    # Store first occurrence
    if emp_id not in name_map:
        name_map[emp_id] = fname


print("Name Mapping:")
print(name_map)

Name Mapping:
{'A001': 'Mr. John', 'A002': 'Mrs. Alice', 'A003': 'Mr. Tom', 'A004': 'Mrs. Nina', 'A005': 'Mrs. Amy'}

In [23]:
# ==================================
# Create TotalProjCost DataFrame
# ==================================

ids = []
names = []
costs = []

for emp_id in total_cost:
    
    ids.append(emp_id)
    names.append(name_map[emp_id])
    costs.append(total_cost[emp_id])


# Create DataFrame
TotalProjCost = pd.DataFrame({
    "ID": ids,
    "First Name": names,
    "Total Cost": costs
})

display(TotalProjCost)

     ID  First Name    Total Cost
0  A001    Mr. John  5.063714e+06
1  A002  Mrs. Alice  2.680000e+06
2  A003     Mr. Tom  5.150000e+06
3  A004   Mrs. Nina  9.500000e+06
4  A005    Mrs. Amy  3.850500e+06

In [24]:
# Save file
TotalProjCost.to_csv("total_project_cost.csv", index=False)

print("Task 9 completed and saved!")

Task 9 completed and saved!

In [25]:
# ==================================
# Task 10 : Find Cities Containing 'o'
# ==================================

# Convert to lowercase and check 'o'
result = df_final[df_final["City"].str.lower().str.contains("o")]

print("Employees Whose City Contains 'o':")
display(result)

Employees Whose City Contains 'o':

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,3,0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,1,150000

In [26]:
print("Task 10 completed successfully!")

Task 10 completed successfully!